config {
  type: "table",
  schema: dataform.projectConfig.vars.goldDataset,
  name: "fact_payment",
  tags: ["gold", "fact"]
}

SELECT
  TO_HEX(MD5(CAST(p.payment_id AS STRING))) AS payment_sk,
  TO_HEX(MD5(CAST(p.order_id AS STRING))) AS order_sk,
  COALESCE(dc.customer_sk, "unknown") AS customer_sk,
  CAST(FORMAT_DATE("%Y%m%d", DATE(p.created_at)) AS INT64) AS payment_date_key,
  p.payment_id,
  p.order_id,
  o.customer_id,
  p.payment_method,
  p.payment_status,
  p.amount,
  p.created_at AS payment_created_at,
  p.updated_at AS payment_updated_at,
  p.cdc_event_ts,
  p.bronze_ingested_at
FROM
  ${ref("payments")} AS p
LEFT JOIN
  ${ref("orders")} AS o
ON
  p.order_id = o.order_id
LEFT JOIN
  ${ref("dim_customer")} AS dc
ON
  o.customer_id = dc.customer_id
  AND p.created_at >= dc.effective_start_at
  AND (dc.effective_end_at IS NULL OR p.created_at < dc.effective_end_at)
