config {
  type: "assertion",
  tags: ["gold", "fact"]
}

SELECT
  order_item_id
FROM
  ${ref("fact_order_item")}
GROUP BY
  order_item_id
HAVING
  COUNT(*) > 1

UNION ALL

SELECT
  order_item_id
FROM
  ${ref("fact_order_item")}
WHERE
  order_item_sk IS NULL
  OR order_sk IS NULL
  OR product_sk IS NULL
  OR customer_sk IS NULL
  OR order_date_key IS NULL
  OR quantity <= 0
  OR unit_price < 0
  OR line_total < 0
